os: linux

language: go

go: "1.14"

notifications:
  email: false

services:
  - docker

jobs:
  include:
    - stage: test
      script: docker-compose up --build && docker-compose exec app bash -c "go test ./integration -bench=."
