os: linux

language: go

go: "1.14"

notifications:
  email: false

services:
  - docker

script:
  - docker-compose up -d
  - cd $GOPATH/src/github.com/VictoryKS/design-practice-3/integration
  - go test -bench=.
