os: linux

language: go

go: "1.14"

notifications:
  email: false

services:
  - docker

jobs:
  include:
    - name: Test
      stage: test
      script: docker-compose up
    - script:
        - sleep 15
        - cd $GOPATH/src/github.com/VictoryKS/design-practice-3/integration
        - go test -bench=.

stages:
  - test
