os: linux

language: go

go: "1.14"

notifications:
  email: false

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose version

stages:
  - build
  - test

jobs:
  include:
    #- stage: build
    #  script: docker-compose up -d
    - stage: test
      script: docker-compose up -d && docker-compose exec app bash -c "go test ./integration -bench=."
