os: linux

language: go

go: "1.14"

notifications:
  email: false

services:
  - docker

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script: docker-compose up -d
    - stage: test
      script: docker-compose up -d && docker-compose exec app bash -c "go test ./integration -bench=."
